# Generated by Django 6.1 on 2026-08-10 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comptes", "0002_remove_utilisateur_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="utilisateur",
            managers=[],
        ),
    ]
