# Generated by Django 6.1 on 2026-08-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portee', models.CharField(choices=[('type', 'Un type de poteau'), ('niveau', 'Un niveau'), ('batiment', 'Un bâtiment'), ('projet', 'Le projet entier')], max_length=20, verbose_name='portée')),
                ('intitule', models.CharField(max_length=200, verbose_name='intitulé figé')),
                ('date_export', models.DateTimeField(auto_now_add=True, verbose_name="date d'export")),
                ('fichier', models.FileField(upload_to='notes/%Y/%m/', verbose_name='fichier PDF')),
            ],
            options={
                'verbose_name': 'export',
                'ordering': ['-date_export'],
            },
        ),
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='date du calcul')),
                ('methode', models.CharField(default='methode_simplifiee', max_length=100, verbose_name='méthode')),
                ('version_moteur', models.CharField(max_length=20, verbose_name='version du moteur de calcul')),
                ('type_section', models.CharField(max_length=30)),
                ('b', models.FloatField(blank=True, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('L0', models.FloatField()),
                ('d_prime', models.FloatField()),
                ('G', models.FloatField()),
                ('Q', models.FloatField()),
                ('fck', models.FloatField()),
                ('fyk', models.FloatField()),
                ('classe_exposition', models.CharField(max_length=10)),
                ('taux_travail_min', models.FloatField()),
                ('As', models.FloatField(verbose_name='As (cm²)')),
                ('NRd', models.FloatField(verbose_name='NRd (kN)')),
                ('NEd', models.FloatField(verbose_name='NEd (kN)')),
                ('as_min_gouverne', models.BooleanField(default=False)),
                ('lambda_elancement', models.FloatField(verbose_name='élancement λ')),
                ('alpha', models.FloatField()),
                ('kh', models.FloatField()),
                ('ks', models.FloatField()),
                ('rho', models.FloatField()),
                ('delta', models.FloatField()),
                ('taux_travail', models.FloatField()),
                ('nombre_barres_longitudinales', models.IntegerField(blank=True, null=True)),
                ('diametre_longitudinal', models.FloatField(blank=True, null=True, verbose_name='Øl (mm)')),
                ('diametre_cadres', models.FloatField(blank=True, null=True, verbose_name='Øt (mm)')),
                ('espacement_central', models.FloatField(blank=True, null=True, verbose_name='espacement central (mm)')),
                ('espacement_extremites', models.FloatField(blank=True, null=True, verbose_name='espacement extrémités (mm)')),
                ('calcule_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calcul',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
