# Generated by Django 6.1 on 2026-08-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculs', '0001_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calcul',
            name='type_poteau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculs', to='projets.typepoteau'),
        ),
        migrations.AddField(
            model_name='export',
            name='calculs',
            field=models.ManyToManyField(related_name='exports', to='calculs.calcul'),
        ),
        migrations.AddField(
            model_name='export',
            name='exporte_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to=settings.AUTH_USER_MODEL),
        ),
    ]
