# Generated by Django 6.1 on 2026-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcul',
            name='ferraillage_impossible',
            field=models.BooleanField(default=False),
        ),
    ]
