# Generated by Django 6.1 on 2026-08-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fck', models.FloatField(blank=True, verbose_name='fck (MPa)')),
                ('fyk', models.FloatField(blank=True, verbose_name='fyk (MPa)')),
                ('classe_exposition', models.CharField(blank=True, max_length=10, verbose_name="classe d'exposition")),
                ('nom', models.CharField(max_length=150, verbose_name='nom du bâtiment')),
            ],
            options={
                'verbose_name': 'bâtiment',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fck', models.FloatField(blank=True, verbose_name='fck (MPa)')),
                ('fyk', models.FloatField(blank=True, verbose_name='fyk (MPa)')),
                ('classe_exposition', models.CharField(blank=True, max_length=10, verbose_name="classe d'exposition")),
                ('nom', models.CharField(max_length=100, verbose_name='nom du niveau')),
                ('ordre', models.IntegerField(default=0, verbose_name="ordre d'affichage")),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='projets.batiment')),
            ],
            options={
                'verbose_name': 'niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('fck', models.FloatField(default=45.0, verbose_name='fck (MPa)')),
                ('fyk', models.FloatField(default=500.0, verbose_name='fyk (MPa)')),
                ('classe_exposition', models.CharField(max_length=10, verbose_name="classe d'exposition")),
                ('membres', models.ManyToManyField(related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='membres')),
            ],
            options={
                'verbose_name': 'projet',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='batiment',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='projets.projet'),
        ),
        migrations.CreateModel(
            name='TypePoteau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom du type')),
                ('calcul_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_courant', to='calculs.calcul', verbose_name='calcul retenu')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_poteaux', to='projets.niveau')),
            ],
            options={
                'verbose_name': 'type de poteau',
            },
        ),
        migrations.CreateModel(
            name='Poteau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fck', models.FloatField(blank=True, verbose_name='fck (MPa)')),
                ('fyk', models.FloatField(blank=True, verbose_name='fyk (MPa)')),
                ('classe_exposition', models.CharField(blank=True, max_length=10, verbose_name="classe d'exposition")),
                ('repere', models.CharField(max_length=50, verbose_name='repère')),
                ('type_section', models.CharField(choices=[('rectangulaire', 'Rectangulaire'), ('circulaire', 'Circulaire')], max_length=20, verbose_name='type de section')),
                ('b', models.FloatField(blank=True, null=True, verbose_name='b (m)')),
                ('h', models.FloatField(blank=True, null=True, verbose_name='h (m)')),
                ('diametre', models.FloatField(blank=True, null=True, verbose_name='D (m)')),
                ('L0', models.FloatField(verbose_name='L0 (m)')),
                ('d_prime', models.FloatField(verbose_name="d' (m)")),
                ('G', models.FloatField(verbose_name='G (kN)')),
                ('Q', models.FloatField(verbose_name='Q (kN)')),
                ('taux_travail_min', models.FloatField(default=1.0, verbose_name='taux de travail minimal visé')),
                ('duree_resistance_feu', models.CharField(blank=True, max_length=10, verbose_name='durée de résistance au feu')),
                ('expose_un_seul_cote', models.BooleanField(default=False, verbose_name='exposé sur un seul côté')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poteaux', to='projets.niveau')),
                ('type_poteau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poteaux_couverts', to='projets.typepoteau')),
            ],
            options={
                'verbose_name': 'poteau',
                'ordering': ['repere'],
            },
        ),
        migrations.AddConstraint(
            model_name='batiment',
            constraint=models.UniqueConstraint(fields=('projet', 'nom'), name='batiment_unique_par_projet'),
        ),
        migrations.AddConstraint(
            model_name='poteau',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('b__isnull', False), ('h__isnull', False), ('type_section', 'rectangulaire')), models.Q(('diametre__isnull', False), ('type_section', 'circulaire')), _connector='OR'), name='dimensions_coherentes_avec_type_section'),
        ),
    ]
