# Generated by Django 6.1 on 2026-08-09 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['ordre'], 'verbose_name': 'niveau', 'verbose_name_plural': 'niveaux'},
        ),
        migrations.AlterModelOptions(
            name='poteau',
            options={'ordering': ['repere'], 'verbose_name': 'poteau', 'verbose_name_plural': 'poteaux'},
        ),
        migrations.AlterModelOptions(
            name='typepoteau',
            options={'verbose_name': 'type de poteau', 'verbose_name_plural': 'types de poteau'},
        ),
        migrations.AlterField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='membres'),
        ),
    ]
