# Generated by Django 6.1 on 2026-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_alter_niveau_options_alter_poteau_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='poteau',
            constraint=models.UniqueConstraint(fields=('niveau', 'repere'), name='repere_unique_par_niveau'),
        ),
    ]
