import type { Poteau, Projet } from "@/types/api";

export const PROJETS_DEMO: Projet[] = [
  {
    id: 1,
    nom: "Airbus Aerospace",
    description: "Montigny",
    date_creation: "2026-03-12T09:15:00Z",
    membres: [1],
    fck: 45,
    fyk: 500,
    classe_exposition: "XC1",
  },
  {
    id: 2,
    nom: "GA Smart Building",
    description: "",
    date_creation: "2026-05-02T14:40:00Z",
    membres: [1, 2],
    fck: 30,
    fyk: 500,
    classe_exposition: "XC3",
  },
];

export const POTEAUX_DEMO: Poteau[] = [
  {
    id: 1,
    niveau: 1,
    type_poteau: null,
    repere: "P1",
    type_section: "rectangulaire",
    b: 0.3,
    h: 0.3,
    diametre: null,
    L0: 3.0,
    d_prime: 0.035,
    G: 850,
    Q: 220,
    taux_travail_min: 1.1,
    duree_resistance_feu: "",
    expose_un_seul_cote: false,
    fck: 30,
    fyk: 500,
    classe_exposition: "XC1",
  },
  {
    id: 2,
    niveau: 1,
    type_poteau: null,
    repere: "P2",
    type_section: "rectangulaire",
    b: 0.45,
    h: 0.3,
    diametre: null,
    L0: 3.0,
    d_prime: 0.04,
    G: 1209,
    Q: 200,
    taux_travail_min: 1.1,
    duree_resistance_feu: "",
    expose_un_seul_cote: false,
    fck: 30,
    fyk: 500,
    classe_exposition: "XC1",
  },
  {
    id: 3,
    niveau: 1,
    type_poteau: null,
    repere: "P3",
    type_section: "circulaire",
    b: null,
    h: null,
    diametre: 0.5,
    L0: 3.0,
    d_prime: 0.04,
    G: 430,
    Q: 95,
    taux_travail_min: 1.1,
    duree_resistance_feu: "",
    expose_un_seul_cote: false,
    fck: 30,
    fyk: 500,
    classe_exposition: "XC1",
  },
];
